[[constraint]]
  name = "github.com/astaxie/beego"
  version = "1.12.0"

[[constraint]]
  name = "github.com/lib/pq"
  version = "1.2.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.4.0"
